name: Fuzzy Docker Image CI 

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.expected_failure }}
    strategy:
      fail-fast: false
      matrix:
        VFC_BACKENDS: ["libinterflop_ieee.so", "libinterflop_mca.so -m rr"]
        FUZZY_LEVEL: [0, 1, 2]
        expected_failure: [false]
        include:
          - FUZZY_LEVEL: 0
            VFC_BACKENDS: 'libinterflop_mca.so -m mca'
            expected_failure: false
          
          - FUZZY_LEVEL: [1, 2]
            VFC_BACKENDS: 'libinterflop_mca.so -m mca'
            expected_failure: true



    name: Fuzzy level ${{ matrix.FUZZY_LEVEL }} | ${{ matrix.VFC_BACKENDS }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for fuzzy level ${{ matrix.FUZZY_LEVEL }}
      run: docker build . --file ./pyafq_docker/Dockerfile.fuzzy-${{ matrix.FUZZY_LEVEL }} --tag pyafq-fuzzy-${{ matrix.FUZZY_LEVEL }}:$(date +%s) --build-arg vfcbackends="${{ matrix.VFC_BACKENDS }}"
